[workspace]
resolver = "3"
members = ["crates/cli", "crates/lib"]

[workspace.package]
version = "0.9.0"
edition = "2024"
license = "MIT"
repository = "https://git.perish.top/PerishFire/concord"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
fs2 = "0.4"
flate2 = "1"
locus = { version = "0", registry = "perish" }
plumb = { version = "0", registry = "perish", features = ["skill"] }
pulldown-cmark = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
sysinfo = { version = "0.30", default-features = false }
tempfile = "3"
tar = "0.4"
toml = "0.9"

[workspace.dependencies.rustix]
version = "1"
features = ["fs"]
